### ISSUE TITLE
Add three finger dragging 

### ISSUE THREAD

**Issue by namtonthat** [yannbertrand/macos-defaults#270]
- [x] I made sure this command is not in the commands list
- [x] I searched and didn't find this command in the listed issues
- [x] I know this `defaults` command exists
- [x] I know this command works on macOS current version
- [ ] I know this command is deprecated on macOS current version

- Folder: Trackpad
- Command: 
```
defaults write com.apple.AppleMultitouchTrackpad DragLock -bool false
defaults write com.apple.AppleMultitouchTrackpad Dragging -bool false
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true
```
- Argument type (if applicable): `bool`
- Examples:
```
   - folder: Trackpad
    name: Trackpad
    description: |
      Accessibility controls for macOS via Magic Trackpad or Magic Mouse.
    keys:
      - key: three-finger-dragging
        domain: com.apple.AppleMultitouchTrackpad
        title: Rearrange windows using three fingers
        param:
          type: bool
        examples:
          - value: true
            text: The ability to drag items using a three-finger gesture is an option for trackpads that support Force Touch.
          - value: false
            default: true
            text: Do nothing upon three finger gesture
        versions: [Ventura, Monterey, Big Sur, Catalina, Mojave]

      - key: dragging
        domain: com.apple.AppleMultitouchTrackpad
        title: Rearrange windows using Drag Lock
        param:
          type: bool
        examples:
          - value: true
            text: Enable window draging
          - value: false
            default: true
            text: Disable window draging
        versions: [Ventura, Monterey, Big Sur, Catalina, Mojave]

      - key: drag-lock
        domain: com.apple.AppleMultitouchTrackpad
        title: Rearrange windows using Drag Lock
        param:
          type: bool
        examples:
          - value: true
            text: Double-tap an item, then drag it without lifting your finger after the second tap; dragging continues when you lift your finger, and stops when you tap the trackpad once.
          - value: false
            default: true
            text: Double-tap an item, then drag it without lifting your finger after the second tap; when you lift your finger, the item stops moving.
        versions: [Ventura, Monterey, Big Sur, Catalina, Mojave]
```
